### ISSUE TITLE
Collision of the yellow block

### ISSUE THREAD

**Issue by adrixdx** [Guille1406/The-Legend-of-Zelda-Hyrule-Conquest#1]
Priority: High
Type: Logic
Frequency: Everytime you do
Results: When you go to the yellow block, you can go through it by northeastern side
Add info:
Status: Open

![yellow block bug](https://cloud.githubusercontent.com/assets/17145775/23994594/db8d3f92-0a45-11e7-9550-eff6852f16fd.jpg)

**Comment by mizquierdo97** [comment]
Fixed
