### ISSUE TITLE
Game Crash while zelda and enemy are jumping

### ISSUE THREAD

**Issue by JaviOrtiz** [Guille1406/The-Legend-of-Zelda-Hyrule-Conquest#19]
Priority: high
Type: Logic
Frequency: when u jump from the third room from the elevated area, and an enemy follows you from there.
Results: game crash
Add info: enemy must follow you to the elevated area, then u mus jump to the flat area and the game crash
Status: Open

**Comment by mizquierdo97** [comment]
Fixed
